### ISSUE TITLE
-- is removed from commands

### ISSUE THREAD

**Issue by hugoduncan** [docopt/docopt.rs#111]
With the usage pattern `cmd <args>...`, a literal "--" passed to args does not appear in the final `Vec` returned by `Docopt` for the `<args>`.

From my reading of the docopt standard, I think this is incorrect behaviour (but I'm no docopt expert).

**Comment by BurntSushi** [comment]
This was recently changed in https://github.com/docopt/docopt.rs/commit/b90c40d375ca18cc29db13d576f8dfd090f5c77a (see the linked issue for context).

Maybe the "right" choice here is to only exclude it when it appears in the usage pattern as a command. I'm not sure.

**Comment by hugoduncan** [comment]
Only excluding it if it appears in the usage pattern would work for me.
