### ISSUE TITLE
Latest docopt fails as a dependency

### ISSUE THREAD

**Issue by hugoduncan** [docopt/docopt.rs#115]
Fails due to recent hyphen changes on cargo.

```
cargo build
Unable to get packages from source

Caused by:
  failed to parse manifest at `/Users/duncan/.cargo/registry/src/github.com-1ecc6299db9ec823/docopt-0.6.55/Cargo.toml`

Caused by:
  target names cannot contain hyphens: docopt-wordlist
```

**Comment by BurntSushi** [comment]
What version of `rustc` are you using? What version of `cargo` are you using? This should be fixed in the newest version of Cargo.

**Comment by hugoduncan** [comment]
Looks like my `rustc` was a day too old.  All seems ok with an update to 2015-03-26.  Thanks.
