### ISSUE TITLE
[feature] get subsections from usage string 

### ISSUE THREAD

**Issue by alexchandel** [docopt/docopt.rs#125]
Consider if you will,
```rust
docopt!(Args derive Debug, "
Naval Fate.

Usage:
  naval_fate ship new <name> <crewman>...
  naval_fate ship <name> move <x> <y> [--speed=<kn>]
  naval_fate ship shoot <x> <y>
  naval_fate mine (set|remove) <x> <y> [--moored|--drifting]
  naval_fate -h | --help
  naval_fate --version

Options:
  -h --help     Show this screen.
  --version     Show version.
  --speed=<kn>  Speed in cochranes [default: 10].
  --moored      Moored (anchored) mine.
  --drifting    Drifting mine.

Examples:
  naval_fate new 'USS Enterprise' Kirk Spock McCoy

Warnings:
  Flux and all other color-changing software must be off.
  The tactical GUI must be running and visible or naval_fate will trigger security shutdown.
   `naval_fate mine set 0 0` may cause self-destruction.

Non-bugs:
  `naval_fate ship shoot` requires command clearance per Starfleet General Order 1207A

Bugs:
  naval_fate may crash if a ship name contains Klingon characters.
");

static WARNINGS: &'static str = "
Warnings:
  Flux and all other color-changing software must be off.
  The tactical GUI must be running and visible or naval_fate will fail unpredictably.
   `naval_fate ship shoot 0 0` will cause self-destruction.
";

fn main() {
    let args: Args = Args::docopt().decode().unwrap_or_else(|e| e.exit());

    if args.cmd_mine {
        println_err!("{}", WARNINGS)
    };

    // do stuff
}
```
with some complexifications for production-level code.

It would be useful to be able to extract individual subsections from the usage string via the `docopt!`-generated struct, rather than have to duplicate these messages. In the case above there's a section that needs to be printed both with the full usage and with certain commands, but other cases are possible. I often run into this when using docopt for deliverable code.

I haven't given much thought regarding integration with the existing API/API plans, but there should be a place in `struct docopt::Docopt` for this, or for related/preferable behavior that @BurntSushi can think of.

**Comment by BurntSushi** [comment]
I think I'd rather not add this to Docopt proper and instead stick to what the spec says.

With that said, I see two ways to fix your problem with a very small amount of work:

1. Use `concat!` to concatenate string constants. e.g., https://github.com/BurntSushi/xsv/blob/master/src/main.rs#L75-L85
2. Roll a custom regex to extract sections from your USAGE string. Something like:

```rust
fn get_section<'a>(usage: &'a str, name: &str) -> &'a str {
    let re = Regex::new(format!(r"(?sm)^{:?}:$.+?\n\n", name)).unwrap();
    re.captures(usage).unwrap().at(0).unwrap()
}
```
