### ISSUE TITLE
Could not compile doctopt_macros

### ISSUE THREAD

**Issue by Ivo-Balbaert** [docopt/docopt.rs#131]
When I include this crate's latest version and compile with stable 1.1.0, I get the error:
// Could not compile `docopt_macros`.
// \src/macro.rs:4:1: 4:52 error: unstable feature
// C:\Users\CVO\.cargo\registry\src\github.com-1ecc6299db9ec823\doco
// \src/macro.rs:4 #![feature(plugin_registrar, quote, rustc_private

//                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// note: this feature may not be used in the stable release channel
// error: aborting due to previous error

Any idea when it will compile with stable?

Thanks,
Ivo

**Comment by BurntSushi** [comment]
> When I include this crate's latest version and compile with stable 1.1.0, I get the error:

`docopt!` is a compiler plugin and compiler plugins do not work on stable Rust. You must use a nightly compiler.

> Any idea when it will compile with stable?

No. Not any time soon. If you want to use stable, then you can only use the `docopt` crate.
