### ISSUE TITLE
Readme talks about 1.0 like it's the future

### ISSUE THREAD

**Issue by Hoverbear** [docopt/docopt.rs#133]
It's now past 1.1!

http://blog.rust-lang.org/2015/05/15/Rust-1.0.html
http://blog.rust-lang.org/2015/06/25/Rust-1.1.html

I was going to make a PR but I don't know what the current state of compatability is.

**Comment by BurntSushi** [comment]
Ah how embarrassing! Thanks for the report!

(The README was apparently written quite a while ago. I found a mention of `uint`!)
