### ISSUE TITLE
"no associated item named `with_empy_ctx`... (v0.6.73 - cargo 0.6.0-nightly - rustc 1.5.0-nightly - arch linux)

### ISSUE THREAD

**Issue by ernestrc** [docopt/docopt.rs#140]
I updated to latest version and crate won't compile:

```
/home/ernestrc/.multirust/toolchains/nightly/cargo/registry/src/github.com-0a35038f75765ae4/docopt_macros-0.6.73/src/macro.rs:285:5: 285:32 error: no associated item named `with_empty_ctxt` found for type `syntax::ast::Ident` in the current scope
/home/ernestrc/.multirust/toolchains/nightly/cargo/registry/src/github.com-0a35038f75765ae4/docopt_macros-0.6.73/src/macro.rs:285     ast::Ident::with_empty_ctxt(token::intern(s))
```

**Comment by BurntSushi** [comment]
Could you please provide more information? What version of `rustc` are you using?

I can compile `docopt` and `docopt_macros` on `rustc 1.5.0-nightly (168a23ebe 2015-10-01)`.

**Comment by ernestrc** [comment]
Docopt v0.6.73 - cargo 0.6.0-nightly - rustc 1.5.0-nightly - arch linux

**Comment by BurntSushi** [comment]
@ernestrc That isn't enough information. The nightly is tied to *nightly* releases. Please show the output of `rustc --version`. If it isn't up to date, please update your version of Rust nightly.

**Comment by ernestrc** [comment]
I thought I had updated with multirust. Now It’s compiling with rustc 1.4.0-nightly (cd138dc44 2015-09-02).
Let me dig in a little bit more.

**Comment by BurntSushi** [comment]
I think everything is good on the current nighty (`b7845f93b 2015-11-15`), so I'm closing this.
