### ISSUE TITLE
Erronous splitting of arguments passed to a sub-command

### ISSUE THREAD

**Issue by dhardy** [docopt/docopt.rs#141]
I *think* [this is a docopt issue](https://github.com/rust-lang/cargo/issues/2027).

The docopt stuff is [here](https://github.com/rust-lang/cargo/blob/master/src/bin/run.rs#L5) (and the actual docopt call [here](https://github.com/rust-lang/cargo/blob/master/src/cargo/lib.rs#L230)).

Short version: quoted strings passed to a command like `./my-cmd -- "some words"` get split in the `arg_args: Vec<String>` parameter (I think).

Sorry I didn't test more but I'm not really familiar with the Cargo code and Docopt looks a bit alien!

**Comment by BurntSushi** [comment]
Can you reproduce a minimal test case? As far as I can see, Docopt, is working correctly:

Code:

```rust
extern crate docopt;
extern crate rustc_serialize;

use docopt::Docopt;

const USAGE: &'static str = "
Usage: prog [--] [<args>...]
";

#[derive(Debug, RustcDecodable)]
struct Args {
    arg_args: Vec<String>,
}

fn main() {
    let args: Args  = Docopt::new(USAGE)
                             .and_then(|d| d.decode())
                             .unwrap_or_else(|e| e.exit());
    println!("{:?}", args);
}
```

Example invocation with properly grouped strings:

```
[andrew@Liger docopt-141] ./target/debug/docopt-141 a "foo baz" c -- x "foo bar" z
Args { arg_args: ["a", "foo baz", "c", "x", "foo bar", "z"] }
```

It's possible that Cargo is passing these strings unquoted to the test binary, which might cause the behavior you're seeing.

**Comment by dhardy** [comment]
Thanks for the reply. In that case I'll try adding some annotations to cargo to check what's going on.

**Comment by dhardy** [comment]
I'm fairly convinced it's not Docopt now. Thanks for the help.
