### ISSUE TITLE
Flag --version not working

### ISSUE THREAD

**Issue by antoyo** [docopt/docopt.rs#146]
Hello.
The `--version` flag does not seem to show the version.
If I test with the first example in the README and launch the following command:

```bash
program --version
```

it does not print the version. It prints:

```
Args { flag_speed: 10, flag_drifting: false, arg_name: [], arg_x: None, arg_y: None, cmd_ship: false, cmd_mine: false }
```

Is there something else to add to make it work?

Thanks.

**Comment by BurntSushi** [comment]
Fixed. `--version` handling is working just fine. But the example never actually set the version.
