### ISSUE TITLE
Localization support

### ISSUE THREAD

**Issue by fubar-coder** [docopt/docopt.rs#157]
What's the preferred solution to provide a localized help text?

**Comment by BurntSushi** [comment]
Without more details about the problem you're trying to solve, it's hard to respond.

There are two issues. One is solveable by the caller, the other isn't yet.

1. When `exit` is called on an error returned by Docopt, it shows the usage info that was initially provided. This is a convenience; the caller doesn't need to call `exit`. Instead, one could read the error output other variations of the usage text.
2. Some errors have additional contextual information, like "--foo is an invalid flag." These are currently hard-coded into the source and there's no easy way to fix them. One way to fix this is to make progress on #149, which will eliminate string-based errors, which would afford one the opportunity to craft their own error messages.

A key thing to note is that neither of these things explicitly address localization inside this library.

**Comment by fubar-coder** [comment]
That was exactly the answer I needed (feared). Thank you for your quick response.
