### ISSUE TITLE
Silent integer wrapping 

### ISSUE THREAD

**Issue by dathinab** [docopt/docopt.rs#159]
Currently the Decoder wraps numbers witch are bigger then the type to decode into.

E.g. for a struct with the filed `arg_n: u8` the input string `"333"` would lead to `77`!!!.

I don't think such a wrapping  is ever intended behaviour an could lead to tricky bugs if e.g. the software is called by another program. Also it happens total silently and at last for me quite unexpected so I feel that it is like a trap witch should be removed/changed :)

**Comment by BurntSushi** [comment]
Definitely a bug. I think the culprit is this unchecked cast: https://github.com/docopt/docopt.rs/blob/master/src/dopt.rs#L707

**Comment by dathinab** [comment]
This has been fixed through other commits, instead of silent wrapping the current result is:
`Could not decode '2000' to u8 for '--test'.`
