### ISSUE TITLE
Can't parse -ve integer in long option

### ISSUE THREAD

**Issue by joew60** [docopt/docopt.rs#175]
On http://try.docopt.org/ the argv
`ship Guardian move 10 50 **--speed=-20**`

is decoded as 
`{
  "--drifting": false, 
  "--help": false, 
  "--moored": false, 
  **"--speed": "-20"**, 
  "--version": false, 
  "<name>": [
    "Guardian"
  ], 
  "<x>": "10", 
  "<y>": "50", 
  "mine": false, 
  "move": true, 
  "new": false, 
  "remove": false, 
  "set": false, 
  "ship": true, 
  "shoot": false
}`

However, docopt.rs reports 
`Could not decode '-20' to i32 for '--speed'`

I know that you cannot handle -20 as a short argument, but discussions seem to suggest that using a long argument is permitted.

Thanks
Joe

**Comment by BurntSushi** [comment]
@joew60 Oh interesting, this is a bug in the decoder trying to decode into a `u64` for all of the number cases, which will certainly fail when given a negative number. See here: https://github.com/docopt/docopt.rs/blob/master/src/dopt.rs#L669

**Comment by BurntSushi** [comment]
Should be all set now. Fixed and on crates.io in `0.6.80`.
