### ISSUE TITLE
Fails to parse a default value containing ']'

### ISSUE THREAD

**Issue by yuttie** [docopt/docopt.rs#187]
I have a line similar to the following in the docopt definition:

```
--regex=<regex>  Filter by a regex [default: ^[0-9]{4}]
```

After parsing an argv, I got the following Debug print of `args`:

```
Args { flag_regex: "^[0-9" }
```

On [Try docopt](http://try.docopt.org/), the default value is parsed as expected.

The following code reproduce this issue:

```rust
extern crate docopt;
extern crate rustc_serialize;

use docopt::Docopt;

const USAGE: &'static str = "
Usage:
  test [--class-regex=<regex>]
  test -h | --help
  test --version

Options:
  --class-regex=<regex>  Filter by a regex [default: ^[0-9]{4}]
  -h --help              Show this screen.
  --version              Show version.
";

#[derive(Debug, RustcDecodable)]
struct Args {
    flag_class_regex: String,
}

fn main() {
    let args: Args = Docopt::new(USAGE)
        .and_then(|d| d.decode())
        .unwrap_or_else(|e| e.exit());
    println!("{:?}", args);
}
```

**Comment by BurntSushi** [comment]
Hmm, I don't have time to try this out, but I wonder if changing `[^]]*` to `.*\]` [here](https://github.com/docopt/docopt.rs/blob/master/src/parse.rs#L251) would fix this.

**Comment by yuttie** [comment]
@BurntSushi Thanks, but that didn't work.
Maybe you mistyped :).  Changing `[^]]*` into `.*` worked instead.

I made a pull request #188.
