### ISSUE TITLE
Broken backwards compatibility in docopt 0.6.86 and later versions

### ISSUE THREAD

**Issue by debris** [docopt/docopt.rs#219]
Hey!

When releasing new version of one of our cli's ([ethabi](https://github.com/paritytech/ethabi)), I noticed that backwards compatibility was broken in version `0.6.86`.

The following code:

```rust

pub const ETHABI: &'static str = r#"
Ethereum ABI coder.
  Copyright 2016-2017 Parity Technologies (UK) Limited

Usage:
    ethabi encode params [-v <type> <param>]... [-l | --lenient]
"#;

#[derive(Debug, RustcDecodable)]
struct Args {
	cmd_encode: bool,
	cmd_params: bool,
	arg_param: Vec<String>,
	arg_type: Vec<String>,
	flag_lenient: bool,
}

let command = "ethabi encode params -v bool 1 -v string gavofyork -v bool 0".split(" ");
let args: Args = Docopt::new(ETHABI)
  .and_then(|d| d.argv(command).decode())
  .unwrap_or_else(|e| e.exit());

assert_eq(args.arg_param.len(), args.arg_type.len(), "{:?} {:?}", args.arg_param, args.arg_type);
```

Works fine in version `0.6.85`, but after upgrading to `0.6.86`, `0.7` or `0.8` it fails with:

```
assertion failed: `(left == right)` (left: `1`, right: `5`): ["bool"] ["1", "string", "gavofyork", "bool", "0"]'
```

Direct link to our broken code: https://github.com/paritytech/ethabi/blob/release_1.2/cli/src/main.rs#L24

**Comment by BurntSushi** [comment]
From looking at the diff between `0.6.85` and `0.6.86`, the only change is a fix to this bug: https://github.com/docopt/docopt.rs/issues/195 So it looks like that caused a regression elsewhere.

I'm not inclined to revert the fix to that bug. I'd rather treat this as a separate bug. I'm not sure when I'll have time to look at it.

**Comment by debris** [comment]
Sure, it's not urgent, cause `0.6.85` still works perfectly fine. I will take a stab at fixing this when I have more time.
