### ISSUE TITLE
Silent breaking change in docopt 0.8.2

### ISSUE THREAD

**Issue by roblabla** [docopt/docopt.rs#235]
Hey,
`cargo-travis` stopped building a couple hours ago because `docopt` 0.8.2 seems to contain a breaking change. When compiling `cargo` 0.22 (a dependency of `cargo-travis`) with `docopt` 0.8.2, I get the following error : 

```
error[E0277]: the trait bound `for<'de> Flags: serde::Deserialize<'de>` is not satisfied
   --> /home/epage/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-0.22.0/src/cargo/lib.rs:123:24
    |
123 |     let flags = docopt.deserialize().map_err(|e| {
    |                        ^^^^^^^^^^^ the trait `for<'de> serde::Deserialize<'de>` is not implemented for `Flags`
    |
    = help: consider adding a `where for<'de> Flags: serde::Deserialize<'de>` bound
    = note: required because of the requirements on the impl of `serde::de::DeserializeOwned` for `Flags`

error: aborting due to previous error

error: failed to compile `cargo-travis v0.0.7`, intermediate artifacts can be found at `/tmp/cargo-install.IOT9kQ0LNqB9`
```

Forcing the version of `docopt` to 0.8.1 resolves the issue.  I think this is related to https://github.com/docopt/docopt.rs/commit/62cf32bd22f96941cec998adda5550ac475d5d5e ?

https://github.com/roblabla/cargo-travis/issues/21

**Comment by BurntSushi** [comment]
Aye, thanks for filing this issue! It looks like that change was made in #222 and I forgot all about it. I've yanked `0.8.2` from crates.io and released `0.8.3` with #222 reverted.
