### ISSUE TITLE
1.1.0 Does not compile

### ISSUE THREAD

**Issue by tcely** [docopt/docopt.rs#251]
https://github.com/docopt/docopt.rs/blob/be4aaf229ef9a8e63ff7c2b0e7f3cd29517cf16a/src/parse.rs#L48

I think the solution here is `use ::regex;`, but I'm not completely familiar with the `2018` edition changes.

**Comment by BurntSushi** [comment]
Please provide enough details to reproduce what you're seeing. As given, this isn't actionable. What command are you running? What version of Rust and Cargo is installed? What is the output?

**Comment by tcely** [comment]
I extracted https://github.com/docopt/docopt.rs/archive/1.1.0.tar.gz and ran `cargo build` with `cargo 1.31.0`.

**Comment by BurntSushi** [comment]
The docopt 1.1.0 release bumped the minimum supported Rust version to 1.32.0.

When reporting build errors in the future, please always include the version of the toolchain you're using.

**Comment by ctz** [comment]
I think requiring a later rustc is a breaking change -- should 1.1.0 have been 2.0.0?

This broke my downstream crate, which has a 1.31.0 minimum and depended upon docopt "1.0". I've changed this to "~1.0" now, but naturally existing releases are still broken.

**Comment by BurntSushi** [comment]
There is no ecosystem consensus on whether bumping the MSRV or not is considered a breaking change. You can read a lengthy conversation about it here: https://github.com/rust-lang-nursery/api-guidelines/issues/123

If you have particular requirements that prevent you from upgrading your version of the Rust compiler, then consider adding them to that thread.
