### ISSUE TITLE
Would `docopt_macros` still require nightly?

### ISSUE THREAD

**Issue by BatmanAoD** [docopt/docopt.rs#252]
I entirely understand your decision to get rid of `docopt_macros`, but if someone else were to implement it, do you believe it could be done with procedural macros now that those are stable, or is there some reason you know of that would force it to remain a compiler plugin?

Also, now that `docopt_macros` no longer exists, there are several issues that look like they can be closed immediately: #162, #210, #213, and #234.

(An unrelated question but not really worth opening a separate issue over: why do you say that the wide docopt project is mostly unmaintained? Is it because docopt/docopt itself hasn't been updated in a long time, or some other reason?)

**Comment by BurntSushi** [comment]
I don't know, sorry. I imagine it could? But I wouldn't know unless I tried, and I'm not going to try.

> (An unrelated question but not really worth opening a separate issue over: why do you say that the wide docopt project is mostly unmaintained? Is it because docopt/docopt itself hasn't been updated in a long time, or some other reason?)

I drew my own conclusion based on publicly available data.
