### ISSUE TITLE
Huge amount of memory used and very slow when parsing many arguments

### ISSUE THREAD

**Issue by cecton** [docopt/docopt.rs#255]
We got an new issue here: https://github.com/paritytech/ethabi/issues/161

And upon investigation I found out that docopts.rs was taking a huge amount of memory to process the arguments and it is very slow. When I use enough arguments, it crashed because it used the whole memory of the system.

I managed to make a test case here in hope I could fix it: https://github.com/cecton/docopt.rs/tree/infinite-loop-filling-memory

If you remove the last five or six `-p` arguments it can complete but it takes more than 40 seconds and used 2.6GB on my machine.

I don't think we will fix this issue in docopt.rs, we think about switching to structopt because it looks rather complicated for me to fix.

**Comment by BurntSushi** [comment]
From the README:

> This crate is unlikely to see significant future evolution. The primary reason to choose this crate for a new project is if you're specifically interested in using docopt syntax for your project. However, the wider docopt project is mostly unmaintained at this point.

> Consider using clap or possibly structopt instead.

Moreover, issues like this have already been filed. For example: #207.

**Comment by cecton** [comment]
Thanks! Sorry for the duplicate, I was looking at "memory" issues
