### ISSUE TITLE
Hidden undocumented options?

### ISSUE THREAD

**Issue by jyn514** [docopt/docopt.rs#257]
(I'm ok if this wontfix and the answer is to use a different library.)

I want to deprecate some command line options that aren't used anymore without removing them altogether. If I remove them from the usage string, then `docopt` of course can't parse them. But I want to allow the flags, just not document them. Is this possible/are you interested in adding it?

**Comment by BurntSushi** [comment]
As far as I know, docopt has no facilities for this. So you're using the wrong tool. docopt is specifically about deriving the argv support from the usage string.

Otherwise, please see the README: https://github.com/docopt/docopt.rs#current-status
