### ISSUE TITLE
Reverse order of usage strings

### ISSUE THREAD

**Issue by nixpulvis** [docopt/docopt.rs#262]
When using multiple "Usage" lines to describe a program, I feel it may make sense to invert the order in which they are processed. This is because the top entry should take precednce over later ones.

Consider the following (taken from a shell program):

I want:
```sh
Usage:
    oursh    [options] [<command_file> [<arguments>...]]
    oursh -s [options] [<arguments>...]
```
So that the primary use case is listed first, however running `oursh -s a b c` gives me:
```
<arguments> => List(["b", "c"])
<command_file> -> Plain(Some("a"))
```

Whereas,
```sh
Usage:
    oursh -s [options] [<arguments>...]
    oursh    [options] [<command_file> [<arguments>...]]
```
does what I want and gives me:
```
<arguments> => List(["a", "b", "c"])
<command_file> => Plain(None)
```

I'm not sure if this is something implementations of Docopt can decide, or if I should escalate this question somewhere else.

Let me know. Thanks.

**Comment by BurntSushi** [comment]
Please see the first line of the README.
