### ISSUE TITLE
flag repetitions inside option are quirky

### ISSUE THREAD

**Issue by BurntSushi** [docopt/docopt.rs#53]
```
Usage: xorfile [-h | -r SECTOR | -n NAME ...]
```

Invoking gives:

```
[andrew@Serval docopt.rs] ./xorfile -n hi 
Names: [hi], Resume: None
[andrew@Serval docopt.rs] ./xorfile -r 5
Names: [], Resume: Some(5)
[andrew@Serval docopt.rs] ./xorfile -n hi -r 5
Invalid arguments.

Usage: xorfile [-h | -r SECTOR | -n NAME ...]
```

The last one should work. If you change the usage to `[-h | -r SECTOR] [-n NAME ...]`, then it works.

**Comment by tgkokk** [comment]
Hmm... Should the last one work? I parse the docstring as: Either `-h`, `-r ` followed by a `SECTOR` or `-n ` followed by many `NAME`s, so it shouldn't work if you pass more than one of those flags, although it's just possible I'm misinterpreting it.

However, this works:

    Usage: xorfile [-h | -r SECTOR | -n NAME ...] ...

Which I parse as: Lots of: either `-h`, `-r ` followed by a `SECTOR` or `-n ` followed by many `NAME`s.

By the way, both Python ([docopt/docopt](https://github.com/docopt/docopt)) and Go ([docopt/docopt.go](https://github.com/docopt/docopt.go)) implementations of Docopt fail to parse either docstring correctly (i.e. the last command doesn't work).

**Comment by BurntSushi** [comment]
Hmm, I interpret the docstring as the union of the following:

* At most one `-h`.
* At most one `-r SECTOR`.
* Any number of `-n NAME`.

I don't think Docopt has a concept corresponding to `--flag val1 val2 ...`. The only way you can get multiple values for a single flag is by explicitly using the flag: `--flag val1 --flag val2 ...`. (N.B. Python's `argparse` supports both modes, IIRC.)

The problem with your alternative usage, `Usage: xorfile [-h | -r SECTOR | -n NAME ...] ...` is that the last `...` applies to the *entire* bracketed flags, which means any of `-h` or `-r` or `-n` can be repeated. Which isn't what I wanted.

**Comment by BurntSushi** [comment]
> By the way, both Python (docopt/docopt) and Go (docopt/docopt.go) implementations of Docopt fail to parse either docstring correctly (i.e. the last command doesn't work).

Yeah, I hadn't tried that. `docopt.rs` varies a tiny bit from other Docopt implementations in that `...` is strictly more expressive. e.g., `docopt.rs` can handle `cp FILE... DIR`, but I don't think the other implementations can. I'm not sure if that's related to this issue though...

**Comment by tgkokk** [comment]
Hmm.. then, I think the docstring should be `Usage: xorfile [-h] [-r SECTOR] [-n NAME...]`, since I think that `[-a | -b]` means you can have at most one of `-a`, `-b` (but not both `-a` and `-b`), and `[-a] [-b]` means you can have at most one of `-a` and at most one of `-b`. I'm looking into the code right now to find how `|` is implemented.

**Comment by BurntSushi** [comment]
You're... absolutely right. I am an idiot and severely confused myself. My brain tricked me into thinking `[ -a | -b ]` meant the union of `-a` and `-b`. This usage captures the behavior I wanted:

```
Usage: xorfile [-h -r SECTOR -n NAME ...]

Options:
    -r SECTOR
    -n NAME
```
