### ISSUE TITLE
Error compiling with latest nightly

### ISSUE THREAD

**Issue by gchp** [docopt/docopt.rs#74]
```
   Compiling docopt v0.6.23 (file:///home/gchp/github.com/gchp/docopt.rs)
/home/gchp/github.com/gchp/docopt.rs/src/synonym.rs:51:38: 51:39 error: obsolete syntax: `|uint| -> bool` closure type syntax
/home/gchp/github.com/gchp/docopt.rs/src/synonym.rs:51     fn with_key<T>(&self, k: &K, with: |&K| -> T) -> T {
                                                                                            ^
note: use unboxed closures instead, no type annotation needed
error: aborting due to previous error
Could not compile `docopt`.
```

Unfortunately, I don't have enough experience with unboxed closures to be able to fix this.

**Comment by BurntSushi** [comment]
Ah... it probably has to change to `fn with_key<T, F>(&self, k: &K, with: F) -> T where F: FnOnce(&K) -> T` or something like that. I'm at work now and probably won't be able to fix it myself until later in the day. (But I can merge PRs more quickly. :-))

**Comment by gchp** [comment]
Yep, that did it! Still some other issues, see here for info: https://github.com/rust-lang/rustc-serialize/pull/16#issuecomment-68860096
Dont think we can do anything about that though...
