### ISSUE TITLE
Mention `rust-serialize` as dependency

### ISSUE THREAD

**Issue by schickling** [docopt/docopt.rs#84]
I think you should mention that people have also to add `rustc-serialize = "*"` to their dependencies in `Cargo.toml` in order to get the examples running. Perhaps also explain in one sentence why that's needed.

**Comment by BurntSushi** [comment]
I'm not sure I follow. `rustc-serialize` is a dependency of `docopt`, so if you install `docopt`, you'll get `rustc-serialize`: https://github.com/docopt/docopt.rs/blob/master/Cargo.toml#L23

**Comment by schickling** [comment]
That's what I was thinking in the beginning. But when I don't add `rustc-serialize` to my dependencies I get the following:

![screenshot 2015-01-22 12 42 00](https://cloud.githubusercontent.com/assets/1567498/5855042/31586c16-a234-11e4-8912-75b872e56fa0.png)

**Comment by BurntSushi** [comment]
Oh. Well, if you have `extern crate SOMETHING` in your code, then `SOMETHING` is a dependency that you need to add to your `Cargo.toml`. This really doesn't have anything to do with Docopt...

I added a small note to the `Cargo.toml` example though.
