### ISSUE TITLE
Error compiling docopt

### ISSUE THREAD

**Issue by he-sk** [docopt/docopt.rs#94]
I'm trying to build a program that uses docopt but it fails with the following error message:

    $ cargo build
       Compiling docopt v0.6.36
    /Users/hesk/.cargo/registry/src/github.com-1ecc6299db9ec823/docopt-0.6.36/src/lib.rs:565:46: 565:59     error: type `collections::string::String` does not implement any method in scope named `into_string`
    /Users/hesk/.cargo/registry/src/github.com-1ecc6299db9ec823/docopt-0.6.36/src/lib.rs:565         ::std::env::args().skip(1).map(|v| v.into_string().unwrap()).collect()
                                                                                                                                      ^~~~~~~~~~~~~
    error: aborting due to previous error
    Could not compile `docopt`.

**Comment by jgillich** [comment]
Fixed by #93.
