### ISSUE TITLE
Outdated macro instructions

### ISSUE THREAD

**Issue by jgillich** [docopt/docopt.rs#95]
I haven't been following Rust for a while so I'm not sure if that is the correct syntax, but this is how I got it working again:

```
#![feature(plugin)]

#![plugin(docopt_macros)]
extern crate docopt_macros;
```

**Comment by BurntSushi** [comment]
You should actually be able to remove `extern crate docopt_macros;`.

**Comment by jgillich** [comment]
You're right, that's neat.
